"""empty message

Revision ID: 31932f231fc0
Revises: 8eefa6b5226f
Create Date: 2023-09-18 14:15:53.467133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31932f231fc0'
down_revision = '8eefa6b5226f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
